### ISSUE TITLE
NRE Labs Relaunch: Technical Execution Plan

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-ops#23]
# NRE Labs Technical Re-Launch Plan

We're re-launching the NRE Labs site in early 2020, and as a result, there are a bunch of technical things that we need to do to pull this off. There will be other activities that will need to take place for the re-launch such as marketing and community-related objectives. This document will focus exclusively on the technical execution plan for the relaunch.

Here's a summary of what we're launching:

- Redesigned web site that fully integrates existing blog, pages, and NRE Labs application
- Redesigned `antidote-web` including widgetization, mobile support, performance improvements, and UX
- New, simpler domain - https://nrelabs.io.
- New, simpler, easier to follow documentation - https://docs.nrelabs.io

Some community/marketing related TODOs that are outside the scope of this document but a good idea to write down just in case:

- [Launch blog](https://github.com/nre-learning/nre-blog/pull/51) - cross post to NRE blog and juniper.net
- Antidote v0.5.0 release blog
- NRE Labs Curriculum v1.1.0 release blog

## Execution Plan

A key component to this execution plan is that we'll be building everything on a new domain, `nrelabs.io`. This will give us a chance to build everything in a safe place before we decide to go live, and will allow us to avoid all kinds of messiness in trying to ensure the old site isn't disrupted during the final stages of development. For the most part, the old site will be left alone, until we're ready to go with the new site, at which point we'll add redirects from the old domain to the new one.

### Phase 1 - Preparation

- [x] Deploy new docs PoC at https://docs.nrelabs.io
- [x] Stand up new site at https://nrelabs.io
- [x] Kick off [0.5.0 platform release](https://community.networkreliability.engineering/t/release-kickoff-v0-5-0/224) cycle
- [x] Kick off [1.0.1 curriculum release](https://community.networkreliability.engineering/t/release-kickoff-v1-0-1/145)
- [x] Move existing deployment to new `prod-old` namespace
- [x] Merge remaining Bitovi work to `antidote-web` and `nre-blog`
- [x] Deploy latest platform code to nrelabs.io and test. Work out any issues.
- [x] Add webssh2 image to prod deployment
- [x] Get webssh2 changes merged upstream or into an nre-learning fork
- [x] Fix `Failed to persist entry: API_ERROR: Not Found` in netlify CMS
- [x] Move forums to new domain and add redirects from old domain (being careful to respect paths - see oswalt.dev cloudflare configuration for reference.  [Change domain in discourse](https://www.discourse.org/c/72acb0759dfd47defc2e201cfdc8f2be/subscription/dns_instructions)
- [x] Remove instances of nlundquist everywhere like in nre-blog. This will help identify if there are any straggling dependencies. There are some references to this in the CSS imports for blog pages.
- [x] Put a better fix into place re: influx in oldprod vs prod. You commented out the influxdb password in new prod because it was squashing metrics from old.
- [x] Add new platform elements to release process
- [x] Finish new docs
- Site updates
  - [x] Go through copy on existing site and update if needed
  - [x] need to add nrelabs in the wild page https://www.packet.com/about/customers/nre-labs/ - update with bitovi case study when available
- [x] Implement cloudflare maintenance page https://github.com/nre-learning/antidote-ops/issues/16 - maybe add an action and chatops alias for activating/deactivating it?

### Phase 2 - Pre-Release Testing

This is a somewhat light form of testing to ensure that lessons are generally where they need to be, and the platform works for everything. It should be done on the master branch of the curriculum and platform, so before anything gets a formal release, but after we generally think the heavy lifting for both is done. This is a way of catching any big issues before we get into release branches, and things get harder to fix.

- [x] lesson 14: Introduction to YAML
- [x] lesson 16: Using Jinja for Configuration Templates
- [x] lesson 17: Version Control with Git
- [x] lesson 19: Introduction to REST APIs
- [x] lesson 23: Linux Basics
- [x] lesson 50: Introduction to BASH
- [x] lesson 12: Network Unit Testing with JSNAPY
- [x] lesson 13: Multi-Vendor Network Automation with NAPALM
- [x] lesson 15: Event-Driven Network Automation with StackStorm
- [x] lesson 24: Junos Automation with PyEZ
- [x] lesson 29: Using Robot Framework for Automated Testing
- [x] lesson 30: Network Automation with Salt
- [x] lesson 31: Terraform & Junos
- [x] lesson 41: Ansible for Network Automation
- [x] lesson 21: Automating the Troubleshooting Chain
- [x] lesson 32: Automated STIG Compliance Validation
- [x] lesson 33: Quick and Easy Device Inventory
- [x] lesson 34: Automated Device Configuration Backup
- [x] lesson 35: Device Specific Template Generation

### Phase 3 - Release and Testing

- [x] Create Antidote 0.5.0 release
- [x] Create Curriculum 1.0.1 release
- [x] Go over existing cluster, evaluate health and reboot nodes if necessary. Spin up a few extra on-demand nodes to help handle launch load
- [x] Go over deployment manifests for EVERYTHING, and ensure everything is set exactly how it should be. Deploy all to `prod` namespace`

### Phase 4 - Post-Release Testing

Each of the below lessons should be tested, now that everything is in a versioned release. This should be done prior to 2/4/2020, so we can hold a formal "go/no-go" on that date during the community standup

- [x] Test the advisor bug that was mentioned in SVL

- [x] lesson 14: Introduction to YAML
- [x] lesson 16: Using Jinja for Configuration Templates
- [x] lesson 17: Version Control with Git
- [x] lesson 19: Introduction to REST APIs
- [x] lesson 23: Linux Basics
- [x] lesson 50: Introduction to BASH
- [x] lesson 12: Network Unit Testing with JSNAPY
- [x] lesson 13: Multi-Vendor Network Automation with NAPALM
- [x] lesson 15: Event-Driven Network Automation with StackStorm
- [x] lesson 24: Junos Automation with PyEZ
- [x] lesson 29: Using Robot Framework for Automated Testing
- [x] lesson 30: Network Automation with Salt
- [x] lesson 31: Terraform & Junos with 4 endpoints.
- [x] lesson 41: Ansible for Network Automation
- [x] lesson 21: Automating the Troubleshooting Chain
- [x] lesson 32: Automated STIG Compliance Validation
- [x] lesson 33: Quick and Easy Device Inventory
- [x] lesson 34: Automated Device Configuration Backup
- [x] lesson 35: Device Specific Template Generation

### Phase 5 - Go-Live

- [x] Disable social st2 rules (will rebuild in Phase 6)
- [x] Disable/delete all of the st2 rules you put in place to fix memory BS from tomcat
- [x] Change domain in twitter account
- [x] Add redirects via cloudflare (all are 302 for the time being) (make sure redirects carry path forward - see oswalt.dev for reference)
  - `labs.networkreliability.engineering` -> `nrelabs.io`
  - `networkreliability.engineering` -> `nrelabs.io`
  - `community.networkreliability.engineering` -> `discuss.nrelabs.io`
- [x] Testing
- [x] Merge https://github.com/nre-learning/antidote/pull/74 and ensure rtd does a build for it
- [x] Mark relevant videos as "public" - not the first L&L video though, that will go out in a few days
- [x] Publish blogs/tweets. Note that if you publish to nrelabs.io first, you might see that tweet go out right away. Better to post packetpushers first, and then manually send tweets about it. Might want to just disable the sensor and build your own scheduled tweets in tweetdeck just this once. Re enable sensor once everything is published.
- [x] Replace link to picture in packetpushers blog once the hugo version is merged to master, so you don't get a broken link once you delete that branch.
- [x] Replace pinned tweet

### Phase 6 - Clean-Up

- [x] Rebuild social st2 rules with relevant schedules/content
- [x] Scale down old cloudflare account. Delete all you can (not redirects, obviously), including the load balancing subscription (or any other subscriptions).
- [x] Get notified on health check fails in cloudflare. OR just set up your own curls - but make sure the controller is part of this too.
- [x] Google search changes, to the new site. Probably want to do some kind of migration so Google knows that the old didn't just die. Also google analytics
- [x] Deprecate the old intro video somehow

**Comment by Mierdin** [comment]
It is time that I close this issue. The bulk of the work for the relaunch is clearly done, and what hasn't been done has been moved to separate issues to deal with individually.

This was a monumental piece of work, and I think well worth it. A great way to kick off 2020, and I deeply appreciate all who helped with this effort.
