### ISSUE TITLE
Infrastructure change to HA k8s cluster and BMaaS provider

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-ops#9]
# TODO

- [x] Stand up new HA k8s cluster
- [ ] Set up new "observer" server with influxdb and grafana configured securely
- [ ] Add configurability to Syringe to point to this new influxdb system
